import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/layout/layout";

export const metadata: Metadata = {
  title: "React Query",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
